config/routes.rb
PalsPad::Application.routes.draw do
  get "pages/home"

  get "pages/help"

  resources :pals

  resources :pads

  root :to => 'pads#new'

end

app/models/pad.rb
class Pad < ActiveRecord::Base
end

app/models/pal.rb
class Pal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pads_controller.rb
class PadsController < ApplicationController
  # GET /pads
  # GET /pads.xml
  def index
    @pads = Pad.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pads }
    end
  end

  # GET /pads/1
  # GET /pads/1.xml
  def show
    @pad = Pad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pad }
    end
  end

  # GET /pads/new
  # GET /pads/new.xml
  def new
    @pad = Pad.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pad }
    end
  end

  # GET /pads/1/edit
  def edit
    @pad = Pad.find(params[:id])
  end

  # POST /pads
  # POST /pads.xml
  def create
    @pad = Pad.new(params[:pad])

    respond_to do |format|
      if @pad.save
        format.html { redirect_to(@pad, :notice => 'Pad was successfully created.') }
        format.xml  { render :xml => @pad, :status => :created, :location => @pad }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pads/1
  # PUT /pads/1.xml
  def update
    @pad = Pad.find(params[:id])

    respond_to do |format|
      if @pad.update_attributes(params[:pad])
        format.html { redirect_to(@pad, :notice => 'Pad was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pads/1
  # DELETE /pads/1.xml
  def destroy
    @pad = Pad.find(params[:id])
    @pad.destroy

    respond_to do |format|
      format.html { redirect_to(pads_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

end

app/controllers/pals_controller.rb
class PalsController < ApplicationController
  # GET /pals
  # GET /pals.xml
  def index
    @pals = Pal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pals }
    end
  end

  # GET /pals/1
  # GET /pals/1.xml
  def show
    @pal = Pal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pal }
    end
  end

  # GET /pals/new
  # GET /pals/new.xml
  def new
    @pal = Pal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pal }
    end
  end

  # GET /pals/1/edit
  def edit
    @pal = Pal.find(params[:id])
  end

  # POST /pals
  # POST /pals.xml
  def create
    @pal = Pal.new(params[:pal])

    respond_to do |format|
      if @pal.save
        format.html { redirect_to(@pal, :notice => 'Pal was successfully created.') }
        format.xml  { render :xml => @pal, :status => :created, :location => @pal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pals/1
  # PUT /pals/1.xml
  def update
    @pal = Pal.find(params[:id])

    respond_to do |format|
      if @pal.update_attributes(params[:pal])
        format.html { redirect_to(@pal, :notice => 'Pal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pals/1
  # DELETE /pals/1.xml
  def destroy
    @pal = Pal.find(params[:id])
    @pal.destroy

    respond_to do |format|
      format.html { redirect_to(pals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pads_helper.rb
module PadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pals_helper.rb
module PalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>business</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/stylesheets/style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">
	<div id="logo">
		<h1>&nbsp;</h1>
  </div>
	<hr />
	<!-- end #logo -->
	<div id="header">
		<div id="menu">
			<ul>
				<li><a href="#" class="first">Home</a></li>
				<li class="current_page_item"><a href="#">Blog</a></li>
				<li><a href="#">Photos</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Links</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		</div>
		<!-- end #menu -->
		<div id="search">
			<form method="get" action="">
				<fieldset>
				<input type="text" name="s" id="search-text" size="15" />
				<input type="submit" id="search-submit" value="GO" />
				</fieldset>
			</form>
		</div>
		<!-- end #search -->
	</div>
	<!-- end #header -->
	<!-- end #header-wrapper -->
	<div id="page">
		<div id="content">
			<div id="banner"><img src="/images/img09.jpg" alt="" /></div>
			<div class="post">
				<h2 class="title"><a href="#">Welcome to Characterized </a></h2>
				<p class="meta">Sunday, April 26, 2009 7:27 AM Posted by <a href="#">Someone</a></p>
				<div class="entry">
					<p>This is <strong>Characterized </strong>, a free, fully standards-compliant template designed by <a href="http://www.worldclasslasik.com">new york lasik surgery</a>, released for free under the  license.  You're free to use this template for anything as long as you link back to <a href="http://www.worldclasslasik.com">my site</a>. Enjoy :)
					Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. </p>
				</div>
			</div>
			<div class="post">
				<h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
				<p class="meta">Sunday, April 26, 2009 7:27 AM Posted by <a href="#">Someone</a></p>
				<div class="entry">
					<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec   consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros.</p>
				</div>
			</div>
			<div class="post">
				<h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
				<p class="meta">Sunday, April 26, 2009 7:27 AM Posted by <a href="#">Someone</a></p>
				<div class="entry">
					<p>Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. </p>
				</div>
			</div>
		</div>
		<!-- end #content -->
		<div id="sidebar">
			<ul>
				<li>
					<h2>Aliquam tempus</h2>
					<p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, volutpat.</p>
				</li>
				<li>
					<h2>Pellenteque ornare </h2>
					<ul>
						<li><a href="#">Nec metus sed donec</a></li>
						<li><a href="#">Magna lacus bibendum mauris</a></li>
						<li><a href="#">Velit semper nisi molestie</a></li>
						<li><a href="#">Eget tempor eget nonummy</a></li>
						<li><a href="#">Nec metus sed donec</a></li>
						<li><a href="#">Velit semper nisi molestie</a></li>
						<li><a href="#">Eget tempor eget nonummy</a></li>
						<li><a href="#">Nec metus sed donec</a></li>
					</ul>
				</li>
				<li>
					<h2>Turpis nulla</h2>
					<ul>
						<li><a href="#">Nec metus sed donec</a></li>
						<li><a href="#">Magna lacus bibendum mauris</a></li>
						<li><a href="#">Velit semper nisi molestie</a></li>
						<li><a href="#">Eget tempor eget nonummy</a></li>
						<li><a href="#">Nec metus sed donec</a></li>
						<li><a href="#">Nec metus sed donec</a></li>
						<li><a href="#">Magna lacus bibendum mauris</a></li>
						<li><a href="#">Velit semper nisi molestie</a></li>
						<li><a href="#">Eget tempor eget nonummy</a></li>
						<li><a href="#">Nec metus sed donec</a></li>
					</ul>
				</li>
			</ul>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end #page -->
	<div id="footer-bgcontent">
	<div id="footer">
		<p>Design by <a href="http://www.worldclasslasik.com">new york lasik</a> and <a href="http://www.getnetset.com">cpa websites</a></p>
	</div>
	</div>
	<!-- end #footer -->
</div>
</body>
</html>

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PalsPad</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pads/_form.html.erb
<%= form_for(@pad) do |f| %>
  <% if @pad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pad.errors.count, "error") %> prohibited this pad from being saved:</h2>

      <ul>
      <% @pad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location_based %><br />
    <%= f.check_box :location_based %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pads/edit.html.erb
<h1>Editing pad</h1>

<%= render 'form' %>

<%= link_to 'Show', @pad %> |
<%= link_to 'Back', pads_path %>

app/views/pads/index.html.erb
<h1>Listing pads</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Location based</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pads.each do |pad| %>
  <tr>
    <td><%= pad.title %></td>
    <td><%= pad.location_based %></td>
    <td><%= pad.content %></td>
    <td><%= link_to 'Show', pad %></td>
    <td><%= link_to 'Edit', edit_pad_path(pad) %></td>
    <td><%= link_to 'Destroy', pad, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pad', new_pad_path %>

app/views/pads/new.html.erb
<h1>New pad</h1>

<%= render 'form' %>

<%= link_to 'Back', pads_path %>

app/views/pads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @pad.title %>
</p>

<p>
  <b>Location based:</b>
  <%= @pad.location_based %>
</p>

<p>
  <b>Content:</b>
  <%= @pad.content %>
</p>


<%= link_to 'Edit', edit_pad_path(@pad) %> |
<%= link_to 'Back', pads_path %>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pals/_form.html.erb
<%= form_for(@pal) do |f| %>
  <% if @pal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pal.errors.count, "error") %> prohibited this pal from being saved:</h2>

      <ul>
      <% @pal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pals/edit.html.erb
<h1>Editing pal</h1>

<%= render 'form' %>

<%= link_to 'Show', @pal %> |
<%= link_to 'Back', pals_path %>

app/views/pals/index.html.erb
<h1>Listing pals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pals.each do |pal| %>
  <tr>
    <td><%= pal.name %></td>
    <td><%= pal.email %></td>
    <td><%= link_to 'Show', pal %></td>
    <td><%= link_to 'Edit', edit_pal_path(pal) %></td>
    <td><%= link_to 'Destroy', pal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pal', new_pal_path %>

app/views/pals/new.html.erb
<h1>New pal</h1>

<%= render 'form' %>

<%= link_to 'Back', pals_path %>

app/views/pals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pal.name %>
</p>

<p>
  <b>Email:</b>
  <%= @pal.email %>
</p>


<%= link_to 'Edit', edit_pal_path(@pal) %> |
<%= link_to 'Back', pals_path %>